default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
tangerineui: styles/tangerineui.scss
tangerineui-blueberry: styles/tangerineui-blueberry.scss
tangerineui-purple: styles/tangerineui-purple.scss
