import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const VARIANTS = [
  { suffix: '', scssDir: 'tangerineui' },
  { suffix: '-purple', scssDir: 'tangerineui-purple' },
  { suffix: '-cherry', scssDir: 'tangerineui-cherry' },
  { suffix: '-lagoon', scssDir: 'tangerineui-lagoon' },
];

const cols = VARIANTS.map(v => readFileSync(`TangerineUI${v.suffix}.css`, 'utf8').split('\n'));
const n = cols[0].length;
for (const c of cols) if (c.length !== n) throw new Error('line count mismatch — files not line-aligned');

const keyFor = (line, i) => {
  const m = line.match(/--([a-z0-9-]+)\s*:/i);
  return `${m ? m[1] : 'line'}_${i}`; // line index guarantees uniqueness
};

const templateLines = [];
const values = VARIANTS.map(() => ({}));
for (let i = 0; i < n; i++) {
  const line = cols.map(c => c[i]);
  if (line.every(s => s === line[0])) { templateLines.push(line[0]); continue; }
  const minLen = Math.min(...line.map(s => s.length));
  let pre = 0;
  while (pre < minLen && line.every(s => s[pre] === line[0][pre])) pre++;
  let suf = 0;
  while (suf < minLen - pre && line.every(s => s[s.length - 1 - suf] === line[0][line[0].length - 1 - suf])) suf++;
  const key = keyFor(line[0], i);
  templateLines.push(line[0].slice(0, pre) + `{{${key}}}` + line[0].slice(line[0].length - suf));
  line.forEach((s, vi) => { values[vi][key] = s.slice(pre, s.length - suf); });
}

mkdirSync('src', { recursive: true });
writeFileSync('src/template.css', templateLines.join('\n'));
const body = VARIANTS.map((v, vi) =>
  `  {\n    suffix: ${JSON.stringify(v.suffix)},\n    scssDir: ${JSON.stringify(v.scssDir)},\n    values: ${JSON.stringify(values[vi], null, 6).replace(/\n/g, '\n    ')},\n  },`
).join('\n');
writeFileSync('src/variants.mjs', `// GENERATED by src/extract.mjs; edit values here, then run \`node src/build.mjs\`.\nexport const variants = [\n${body}\n];\n`);
console.log(`template lines: ${n}; placeholder keys: ${Object.keys(values[0]).length}`);
